"""create_albums_table

Revision ID: 12d5748fc624
Revises: 
Create Date: 2026-03-25 12:50:18.144351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d5748fc624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('cover_art_thumbnail_url', sa.Text(), nullable=True),
    sa.Column('cover_art_url', sa.Text(), nullable=True),
    sa.Column('discogs_release_id', sa.String(length=50), nullable=False),
    sa.Column('genre_tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('tracklist', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_album_artist', 'albums', ['artist'], unique=False)
    op.create_index('idx_album_title', 'albums', ['title'], unique=False)
    op.create_index('idx_album_year', 'albums', ['year'], unique=False)
    op.create_index(op.f('ix_albums_discogs_release_id'), 'albums', ['discogs_release_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_discogs_release_id'), table_name='albums')
    op.drop_index('idx_album_year', table_name='albums')
    op.drop_index('idx_album_title', table_name='albums')
    op.drop_index('idx_album_artist', table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
