/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/album-filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Album Filters
         * @description Return available genre and decade filter values for the collection.
         */
        get: operations["get_album_filters_api_album_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Albums
         * @description List albums with optional search, genre, and decade filters.
         */
        get: operations["list_albums_api_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Album
         * @description Retrieve a single album by ID.
         */
        get: operations["get_album_api_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/verify-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Pin
         * @description Verify the host PIN and return a session token.
         *
         *     Rate limited to 5 attempts per IP per 60 seconds with a deliberate
         *     500ms delay on every attempt. Only one active host session at a time.
         */
        post: operations["verify_pin_api_host_verify_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/now-playing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote To Now Playing
         * @description Promote a queue item to now playing (host action).
         */
        post: operations["promote_to_now_playing_api_host_now_playing_post"];
        /**
         * Clear Now Playing
         * @description Clear the currently playing album (host action).
         */
        delete: operations["clear_now_playing_api_host_now_playing_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/queue/{queue_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Skip Queue Item
         * @description Remove any queue item regardless of ownership (host action).
         */
        delete: operations["skip_queue_item_api_host_queue__queue_item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return the full queue state including now playing and vote info.
         */
        get: operations["get_queue_api_queue_get"];
        put?: never;
        /**
         * Add To Queue
         * @description Add an album to the queue.
         */
        post: operations["add_to_queue_api_queue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{queue_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove From Queue
         * @description Cancel a queue request (only the requester can cancel).
         */
        delete: operations["remove_from_queue_api_queue__queue_item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Stream
         * @description SSE endpoint for real-time event streaming.
         *
         *     Each connected client gets a dedicated message queue. Events are
         *     pushed by the broadcaster when queue/vote/sync state changes.
         *     Connection limits are enforced (50 global, 3 per IP).
         */
        get: operations["event_stream_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Trigger a full Discogs collection sync.
         *
         *     Fetches all pages of the host's collection and upserts albums.
         *     Requires host authentication. Broadcasts collection_sync event on success.
         */
        post: operations["trigger_sync_api_host_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{queue_item_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cast Vote
         * @description Cast or update a vote on a queue item.
         */
        put: operations["cast_vote_api_queue__queue_item_id__vote_put"];
        post?: never;
        /**
         * Remove Vote
         * @description Remove a vote from a queue item.
         */
        delete: operations["remove_vote_api_queue__queue_item_id__vote_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlbumFilterGetResponse
         * @description Response schema for available filter values (genres and decades).
         */
        AlbumFilterGetResponse: {
            /** Decades */
            decades: number[];
            /** Genres */
            genres: components["schemas"]["GenreCount"][];
        };
        /**
         * AlbumGetResponse
         * @description Response schema for a single album with all fields.
         */
        AlbumGetResponse: {
            /** Artist */
            artist: string;
            /** Cover Art Thumbnail Url */
            cover_art_thumbnail_url: string | null;
            /** Cover Art Url */
            cover_art_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Discogs Release Id */
            discogs_release_id: string;
            /** Genre Tags */
            genre_tags: string[] | null;
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Style Tags */
            style_tags: string[] | null;
            /** Title */
            title: string;
            /** Tracklist */
            tracklist: {
                [key: string]: string;
            }[] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Year */
            year: number | null;
        };
        /**
         * AlbumListResponse
         * @description Response schema for a list of albums.
         */
        AlbumListResponse: {
            /** Albums */
            albums: components["schemas"]["AlbumGetResponse"][];
            /** Count */
            count: number;
        };
        /**
         * AlbumSummary
         * @description Minimal album info embedded in queue responses.
         */
        AlbumSummary: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Cover Art Thumbnail Url */
            cover_art_thumbnail_url: string | null;
            /** Year */
            year: number | null;
        };
        /**
         * CollectionSyncTriggerResponse
         * @description Response schema for triggering a collection sync.
         */
        CollectionSyncTriggerResponse: {
            /** Albums Synced */
            albums_synced: number;
            /** Status */
            status: string;
        };
        /**
         * GenreCount
         * @description A genre tag paired with its album count.
         */
        GenreCount: {
            /** Genre */
            genre: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HostPinVerifyRequest
         * @description Request to verify a host PIN.
         */
        HostPinVerifyRequest: {
            /** Pin */
            pin: string;
        };
        /**
         * HostPinVerifyResponse
         * @description Response containing the host session token.
         */
        HostPinVerifyResponse: {
            /** Token */
            token: string;
        };
        /**
         * NowPlayingGetResponse
         * @description The currently playing album.
         */
        NowPlayingGetResponse: {
            album: components["schemas"]["AlbumSummary"];
            /**
             * Promoted At
             * Format: date-time
             */
            promoted_at: string;
        };
        /**
         * QueueItemCreateRequest
         * @description Request to add an album to the queue.
         */
        QueueItemCreateRequest: {
            /** Album Id */
            album_id: number;
        };
        /**
         * QueueItemGetResponse
         * @description A single queue item with album info and vote state.
         */
        QueueItemGetResponse: {
            /** Id */
            id: number;
            album: components["schemas"]["AlbumSummary"];
            /** Requested By Ip */
            requested_by_ip: string;
            votes: components["schemas"]["VoteGetResponse"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * QueueItemPromoteRequest
         * @description Request to promote a queue item to now playing.
         */
        QueueItemPromoteRequest: {
            /** Queue Item Id */
            queue_item_id: number;
        };
        /**
         * QueueStateResponse
         * @description Full queue state: now playing + ordered queue items.
         */
        QueueStateResponse: {
            now_playing: components["schemas"]["NowPlayingGetResponse"] | null;
            /** Queue */
            queue: components["schemas"]["QueueItemGetResponse"][];
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoteCastRequest
         * @description Request to cast or change a vote.
         */
        VoteCastRequest: {
            /**
             * Value
             * @enum {integer}
             */
            value: 1 | -1;
        };
        /**
         * VoteGetResponse
         * @description Vote counts and the requesting client's vote on a queue item.
         */
        VoteGetResponse: {
            /** Up Count */
            up_count: number;
            /** Down Count */
            down_count: number;
            /** My Vote */
            my_vote: (1 | -1) | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_album_filters_api_album_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumFilterGetResponse"];
                };
            };
        };
    };
    list_albums_api_albums_get: {
        parameters: {
            query?: {
                decade?: number[] | null;
                genre?: string[] | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_album_api_albums__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_pin_api_host_verify_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostPinVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostPinVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_to_now_playing_api_host_now_playing_post: {
        parameters: {
            query?: never;
            header?: {
                "x-host-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueItemPromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_now_playing_api_host_now_playing_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-host-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_queue_item_api_host_queue__queue_item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-host-token"?: string | null;
            };
            path: {
                queue_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_api_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStateResponse"];
                };
            };
        };
    };
    add_to_queue_api_queue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_queue_api_queue__queue_item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queue_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_sync_api_host_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-host-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionSyncTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cast_vote_api_queue__queue_item_id__vote_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queue_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteCastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_vote_api_queue__queue_item_id__vote_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queue_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
